CREATE USER UNIVERSIDADE IDENTIFIED BY senha123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP

ALTER USER UNIVERSIDADE QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO UNIVERSIDADE;

ALTER USER UNIVERSIDADE DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;